### ISSUE TITLE
Aeotec Button

### ISSUE THREAD

**Issue by therealthepaul** [iklein99/homebridge-smartthings#1]
**Is your feature request related to a problem? Please describe:**
Please support the new Aeotec Button (available on Amazon) which is a replacement for the discontinued SmartThings button.

**Describe the solution you'd like:**
The button is simple, supports three states (single press, double press, long press). Implementation is to simply expose these states to HomeKit through HomeBridge using this great plugin you have going here.

**Describe alternatives you've considered:**
There is not other alternative that I can see. Other than creating yet another plugin. But yours is the best, most updated plugin in the ecosystem.

**Additional context:**
I'd be happy to purchase the Aeotec Button for you so you can have it to test with. Reach out and let me know how to do so.

**Comment by iklein99** [comment]
Thanks for the request.   I"ll have a look and let you know soon.  Cheers!

**Comment by iklein99** [comment]
So, after looking at this. the issue is that in order to consume events from a device, I need to implement subscriptions in Smartthings, which requires a dedicated end point.  The plugin as of now is really one-way.  When homekit wants status, it goes out and gets it.  But if you aren't in homekit and press a button or turn something on, nothing get sent to homekit until it requests an update.  Implementing a subscription reqiuires a Smartthings Smart App and a dedicated end point, which will mean dedicated services in the cloud which will cost me $$ ongoing.  I'll look into it, but it isn't looking promising.

**Comment by therealthepaul** [comment]
Thanks for the detailed reply, I really appreciate it.
