### ISSUE TITLE
Device Limit

### ISSUE THREAD

**Issue by DOCNY** [iklein99/homebridge-smartthings#110]
Hello,

I recently switched from the old Smartthings Homebridge to this one. I found out that there is a limit to the number of devices (I am guessing 150). The problem is that I have a lot devices on Smartthings from other services such as harmony, Samsung TVs, ring and Sonos etc on  that somehow make the quota but wouldn't wanna transfer to HomeKit and this results in reaching the cap and thus not exposing the some of the z wave devices that won't  show up on HomeKit. If I delete one of these device and restart homebridge, it adds one extra device (one for one). I was hoping putting such devices on ignore list will fix this problem and although it does remove these redundant devices from the list, it still counts towards the quota. I have them on Smartthings so they compliment the automation process.

Please advise on any work around or a fix.

**Comment by coryabooth** [comment]
https://github.com/homebridge/homebridge

Limitations

One bridge can only expose 150 accessories due to a HomeKit limit. You can however run your plugins as a Child Bridge or run Multiple Homebridge Instances to get around this limitation.

**Comment by DOCNY** [comment]
Correct. My work around would have been running multiple homebridge instances but I see the following behavior.

Let's say I have a total of 200 devices. This plugin seems to pull them in the same orders. Ignore device is taken off the list but still somehow counts towards the quota. The only time it allows a new device added to HomeKit is if an included device is deleted from Samrtthings.

Now let's say devices numbered  1-25 and 151-200 (total of 75) are devices I want exposed to HomeKit  and 26-150 are devices that I don't want exposed such as Sonos, harmony scenes, ring devices etc. The convention would be to put devices 25-150 on ignore list and I would still meet the limit. However, it does not happen.

Similarly, creating a second homebrdige instance where even the devices 1-25 are ignored, it does not pull devices 151 onward because it pulls them in the same order.

**Comment by iklein99** [comment]
Did you try restarting a couple of times after you add the devices to the ignore list?  If you start homebridge up the first time without the ingnore list, it will try to add all of the devices.  THen if you add the devices to ignore and restart, it will try to add all of the new devices, but will fail because the devices you want to ignore are still registered.  However, the next thing it will do is unregister the previously registered devices that you now want to ignore.  If you restart once more, it will add the new devices and not add the ones you have in the ignore list.

**Comment by DOCNY** [comment]
Thank you!
Unregistering and adding ignore list first before running the bridge did the trick.
