### ISSUE TITLE
Add Support for Sprinklers

### ISSUE THREAD

**Issue by kevinjonsutton** [iklein99/homebridge-smartthings#75]
Any chance you can add support for sprinklers? I have my rachio sprinkler in SmartThings and it actually comes over to Homekit through your plugin but as a switch instead of a sprinkler. It would be great if they can come in as the sprinkler device type in Homekit. I can send you the log of how they are reported to SmartThings under debug mode if that would help and can do any testing you need. Thanks!

**Comment by iklein99** [comment]
I can look at it but just so you know Rachio has a plug-in.  I use that at my house.   Sent from my iPhoneOn Oct 31, 2022, at 5:47 PM, kevinjonsutton ***@***.***> wrote:﻿
Any chance you can add support for sprinklers? I have my rachio sprinkler in SmartThings and it actually comes over to Homekit through your plugin but as a switch instead of a sprinkler. It would be great if they can come in as the sprinkler device type in Homekit. I can send you the log of how they are reported to SmartThings under debug mode if that would help and can do any testing you need. Thanks!

**Comment by kevinjonsutton** [comment]
Yes, I'm aware of the plugin and have tried it before but it doesn't work well for me. I figure since the rachio sprinklers from SmartThings already show in Homekit as a switch via your plugin, changing the device type to show as a sprinkler would be great because they work every time I use them via your plugin. Thanks for looking into it.

**Comment by iklein99** [comment]
Supported in 1.4.12.  Note that you'll want to exclude the devices once to unregister them then add them back in.  Otherwise, they will look like devices that have switches and valves.
